name: CSCBattlegrounds
version: '${project.version}'
main: dev.ethans.cscbattlegrounds.CSCBattlegroundsPlugin
api-version: '1.20'

commands:
  playerspawn:
    description: Sets current location as a potential player spawn point
    usage: /<command>
    permission: cscbattlegrounds.admin

  chestspawn:
    description: Sets current location as a potential chest spawn point
    usage: /<command>
    permission: cscbattlegrounds.admin
