WORLD_BORDER:
  TIME_UNTIL_SHRINK: 60
  SHRINK_INTERVAL: 5
  SHRINK_TIME: 15
  SHRINK_AMOUNT: 5
  INITIAL_SIZE: 4000
  MINIMUM_SIZE: 50

TEAMS:
  MAX_TEAM_SIZE: 2
  MAX_TEAMS: 10

DAY_NIGHT_CYCLE:
  MINUTES_PER_DAY: 45
  MINUTES_PER_NIGHT: 15